import React from 'react';
import { Shield, ArrowLeft, Lock, FileText, Scale } from 'lucide-react';

interface LegalProps {
  onBack: () => void;
}

export function Legal({ onBack }: LegalProps) {
  return (
    <div className="min-h-screen bg-[#050B10] text-white p-6 md:p-12 overflow-y-auto">
      <div className="max-w-4xl mx-auto space-y-12 pb-24">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <button 
            onClick={onBack}
            className="group flex items-center gap-2 text-white/40 hover:text-white transition-colors w-fit"
          >
            <ArrowLeft className="h-5 w-5 group-hover:-translate-x-1 transition-transform" />
            <span className="font-black italic uppercase tracking-wider text-sm">Return to Command</span>
          </button>
          <div className="flex items-center gap-4 bg-white/5 border border-white/10 px-6 py-3 rounded-2xl">
            <Shield className="h-6 w-6 text-mint" />
            <span className="font-black italic uppercase tracking-widest text-lg">Legal Framework 2.0</span>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-12">
          {/* Navigation Sidebar */}
          <div className="md:col-span-1 space-y-4">
            <div className="sticky top-12 space-y-2">
              <h1 className="text-4xl font-black italic uppercase leading-none mb-8">Trust &<br/><span className="text-mint">Transparency</span></h1>
              <nav className="space-y-1">
                <a href="#terms" className="flex items-center gap-3 p-3 rounded-xl hover:bg-white/5 transition-colors group">
                  <FileText className="h-4 w-4 text-white/20 group-hover:text-mint transition-colors" />
                  <span className="text-sm font-bold uppercase tracking-widest">Terms of Service</span>
                </a>
                <a href="#privacy" className="flex items-center gap-3 p-3 rounded-xl hover:bg-white/5 transition-colors group">
                  <Lock className="h-4 w-4 text-white/20 group-hover:text-mint transition-colors" />
                  <span className="text-sm font-bold uppercase tracking-widest">Privacy Policy</span>
                </a>
                <a href="#compliance" className="flex items-center gap-3 p-3 rounded-xl hover:bg-white/5 transition-colors group">
                  <Scale className="h-4 w-4 text-white/20 group-hover:text-mint transition-colors" />
                  <span className="text-sm font-bold uppercase tracking-widest">AI & Ethics</span>
                </a>
              </nav>
            </div>
          </div>

          {/* Content */}
          <div className="md:col-span-2 space-y-16">
            {/* Terms of Service */}
            <section id="terms" className="space-y-6">
              <h2 className="text-2xl font-black italic uppercase border-b border-white/10 pb-4 flex items-center gap-3">
                <div className="w-2 h-2 bg-mint rounded-full shadow-[0_0_10px_#22E4A2]"></div>
                Terms of Service
              </h2>
              <div className="prose prose-invert max-w-none text-white/60 font-medium leading-relaxed space-y-4">
                <p>Welcome to ClauseLens. By accessing our platform, you agree to these terms. Please read them carefully.</p>
                
                <h3 className="text-white font-black uppercase text-sm tracking-wider mt-8">1. Service Description</h3>
                <p>ClauseLens provides AI-driven analysis of digital privacy policies and terms of service. Our tool is designed to highlight potential risks and summarize complex legal data for informational purposes.</p>

                <h3 className="text-white font-black uppercase text-sm tracking-wider mt-8">2. Not Legal Advice</h3>
                <p className="bg-white/5 p-4 rounded-xl border border-white/10 text-mint italic">
                  IMPORTANT: The analysis provided by ClauseLens is generated by Artificial Intelligence. It does NOT constitute legal advice. You should consult with a qualified legal professional for any specific legal concerns or interpretations.
                </p>

                <h3 className="text-white font-black uppercase text-sm tracking-wider mt-8">3. User Obligations</h3>
                <p>You agree not to use ClauseLens for any illegal activities or to attempt to reverse-engineer our proprietary scoring algorithms.</p>
              </div>
            </section>

            {/* Privacy Policy */}
            <section id="privacy" className="space-y-6">
              <h2 className="text-2xl font-black italic uppercase border-b border-white/10 pb-4 flex items-center gap-3">
                <div className="w-2 h-2 bg-mint rounded-full shadow-[0_0_10px_#22E4A2]"></div>
                Privacy Policy
              </h2>
              <div className="prose prose-invert max-w-none text-white/60 font-medium leading-relaxed space-y-4">
                <p>Your privacy is central to our mission. We believe in radical transparency about your data.</p>

                <h3 className="text-white font-black uppercase text-sm tracking-wider mt-8">1. Data Collection</h3>
                <p>We collect your email address and profile information via Google Sign-In to provide personalized history and secure access to our analysis engine.</p>

                <h3 className="text-white font-black uppercase text-sm tracking-wider mt-8">2. Browsing & URL Data</h3>
                <p>When you analyze a website, we process the URL and the content of the publicly available terms on that site. We do not track your personal browsing history across other websites.</p>

                <h3 className="text-white font-black uppercase text-sm tracking-wider mt-8">3. Third-Party Intelligence</h3>
                <p>We utilize standardized AI models (Groq Llama-3 / Gemini) to process policy text. These providers do not use your personal identity data for training purposes through our integration.</p>
              </div>
            </section>

            {/* AI Ethics */}
            <section id="compliance" className="space-y-6">
              <h2 className="text-2xl font-black italic uppercase border-b border-white/10 pb-4 flex items-center gap-3">
                <div className="w-2 h-2 bg-mint rounded-full shadow-[0_0_10px_#22E4A2]"></div>
                AI Governance
              </h2>
              <div className="prose prose-invert max-w-none text-white/60 font-medium leading-relaxed space-y-4">
                <p>As an AI-first application, we commit to algorithmic fairness and transparency. Our risk scores are based on open-source datasets and established privacy frameworks.</p>
                <p className="border-l-4 border-mint pl-6 italic">
                  Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
